// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

/*
Package com_example_grpc is a generated protocol buffer package.

It is generated from these files:
	greeter.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package com_example_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sentiment int32

const (
	Sentiment_HAPPY  Sentiment = 0
	Sentiment_SLEEPY Sentiment = 1
	Sentiment_ANGRY  Sentiment = 2
)

var Sentiment_name = map[int32]string{
	0: "HAPPY",
	1: "SLEEPY",
	2: "ANGRY",
}
var Sentiment_value = map[string]int32{
	"HAPPY":  0,
	"SLEEPY": 1,
	"ANGRY":  2,
}

func (x Sentiment) String() string {
	return proto.EnumName(Sentiment_name, int32(x))
}
func (Sentiment) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloRequest struct {
	Name        string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age         int32             `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Hobbies     []string          `protobuf:"bytes,3,rep,name=hobbies" json:"hobbies,omitempty"`
	BagOfTricks map[string]string `protobuf:"bytes,4,rep,name=bagOfTricks" json:"bagOfTricks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sentiment   Sentiment         `protobuf:"varint,5,opt,name=sentiment,enum=com.example.grpc.Sentiment" json:"sentiment,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *HelloRequest) GetHobbies() []string {
	if m != nil {
		return m.Hobbies
	}
	return nil
}

func (m *HelloRequest) GetBagOfTricks() map[string]string {
	if m != nil {
		return m.BagOfTricks
	}
	return nil
}

func (m *HelloRequest) GetSentiment() Sentiment {
	if m != nil {
		return m.Sentiment
	}
	return Sentiment_HAPPY
}

type HelloResponse struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "com.example.grpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "com.example.grpc.HelloResponse")
	proto.RegisterEnum("com.example.grpc.Sentiment", Sentiment_name, Sentiment_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GreetingService service

type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Goodbye(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/com.example.grpc.GreetingService/greeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) Goodbye(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/com.example.grpc.GreetingService/goodbye", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreetingService service

type GreetingServiceServer interface {
	Greeting(context.Context, *HelloRequest) (*HelloResponse, error)
	Goodbye(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.grpc.GreetingService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Greeting(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetingService_Goodbye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Goodbye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.grpc.GreetingService/Goodbye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Goodbye(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.example.grpc.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
		{
			MethodName: "goodbye",
			Handler:    _GreetingService_Goodbye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x6b, 0xda, 0x50,
	0x14, 0xc7, 0x77, 0x13, 0xa3, 0xcb, 0x71, 0xce, 0x70, 0xd9, 0x43, 0x50, 0xd8, 0x82, 0x4f, 0x61,
	0x63, 0x19, 0x38, 0x18, 0xdb, 0x1e, 0x06, 0x0a, 0xa2, 0xac, 0xd2, 0xa6, 0xd7, 0x82, 0xf8, 0x98,
	0xc4, 0xd3, 0x18, 0x4c, 0x72, 0xd3, 0x9b, 0x68, 0xeb, 0xff, 0xd2, 0xa7, 0x3e, 0xf6, 0xaf, 0x2c,
	0x89, 0xf1, 0x07, 0x96, 0xf6, 0xa5, 0x6f, 0xdf, 0x73, 0xef, 0xf7, 0x7c, 0xce, 0x0f, 0x0e, 0x34,
	0x7c, 0x81, 0x98, 0xa1, 0xb0, 0x12, 0xc1, 0x33, 0x4e, 0x35, 0x8f, 0x47, 0x16, 0xde, 0x39, 0x51,
	0x12, 0xa2, 0xe5, 0x8b, 0xc4, 0xeb, 0xdc, 0x4b, 0xf0, 0x61, 0x84, 0x61, 0xc8, 0x19, 0xde, 0xac,
	0x30, 0xcd, 0x28, 0x85, 0x4a, 0xec, 0x44, 0xa8, 0x13, 0x83, 0x98, 0x2a, 0x2b, 0x34, 0xd5, 0x40,
	0x76, 0x7c, 0xd4, 0x25, 0x83, 0x98, 0x0a, 0xcb, 0x25, 0xd5, 0xa1, 0xb6, 0xe0, 0xae, 0x1b, 0x60,
	0xaa, 0xcb, 0x86, 0x6c, 0xaa, 0x6c, 0x17, 0xd2, 0x4b, 0xa8, 0xbb, 0x8e, 0x7f, 0x71, 0x7d, 0x25,
	0x02, 0x6f, 0x99, 0xea, 0x15, 0x43, 0x36, 0xeb, 0xdd, 0x1f, 0xd6, 0x69, 0x61, 0xeb, 0xb8, 0xa8,
	0xd5, 0x3f, 0x64, 0x0c, 0xe2, 0x4c, 0x6c, 0xd8, 0x31, 0x83, 0xfe, 0x01, 0x35, 0xc5, 0x38, 0x0b,
	0x22, 0x8c, 0x33, 0x5d, 0x31, 0x88, 0xf9, 0xb1, 0xdb, 0x7e, 0x0e, 0x9c, 0xec, 0x2c, 0xec, 0xe0,
	0x6e, 0xfd, 0x03, 0xed, 0x94, 0x9d, 0x4f, 0xb3, 0xc4, 0x4d, 0x39, 0x60, 0x2e, 0xe9, 0x27, 0x50,
	0xd6, 0x4e, 0xb8, 0xda, 0x4e, 0xa8, 0xb2, 0x6d, 0xf0, 0x57, 0xfa, 0x4d, 0x3a, 0xdf, 0xa0, 0x51,
	0x36, 0x9a, 0x26, 0x3c, 0x4e, 0x91, 0xb6, 0xe0, 0x7d, 0xb1, 0xd2, 0x20, 0xf6, 0x4b, 0xc2, 0x3e,
	0xfe, 0xfa, 0x1d, 0xd4, 0x7d, 0x13, 0x54, 0x05, 0x65, 0xd4, 0xb3, 0xed, 0x99, 0xf6, 0x8e, 0x02,
	0x54, 0x27, 0xe3, 0xc1, 0xc0, 0x9e, 0x69, 0x24, 0x7f, 0xee, 0x9d, 0x0f, 0xd9, 0x4c, 0x93, 0xba,
	0x8f, 0x04, 0x9a, 0xc3, 0x32, 0x77, 0x82, 0x62, 0x1d, 0x78, 0x48, 0xcf, 0x0e, 0x78, 0xfa, 0xf9,
	0xf5, 0xa5, 0xb5, 0xbe, 0xbc, 0xf8, 0x5f, 0xf6, 0xfa, 0x1f, 0x6a, 0x3e, 0xe7, 0x73, 0x77, 0x83,
	0x6f, 0x66, 0xf5, 0x7f, 0x41, 0x3b, 0xe0, 0xdb, 0x8f, 0xd2, 0x95, 0x5a, 0x8b, 0xdc, 0x71, 0xcb,
	0x45, 0x38, 0xef, 0x37, 0x0b, 0xf7, 0x34, 0xd7, 0x76, 0x7e, 0x69, 0x36, 0x79, 0x90, 0xe4, 0xd1,
	0x78, 0xea, 0x56, 0x8b, 0xc3, 0xfb, 0xf9, 0x14, 0x00, 0x00, 0xff, 0xff, 0x99, 0x00, 0x0b, 0x83,
	0x89, 0x02, 0x00, 0x00,
}
